#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class OnEventJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.OnEventJobsPage_Title);
    List<OnEventJobDto> onEventJobs;

    int from, perPage;

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    Pager pager = null;

    using (var connection = Storage.GetConnection())
    {
        var storageConnection = connection as JobStorageConnection;
        if (storageConnection != null)
        {
            pager = new Pager(from, perPage, storageConnection.GetOnEventJobCount());
            onEventJobs = storageConnection.GetOnEventJobs(pager.FromRecord, pager.FromRecord + pager.RecordsPerPage);
        }
        else
        {
            onEventJobs = connection.GetOnEventJobs();
        }
    }


            
            #line default
            #line hidden
WriteLiteral(@"<style>
    .table {
        /*table-layout: fixed;*/
    }

        .table td {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
</style>
<div class=""row"">
    <div class=""col-md-12"">
        <h1 class=""page-header"">");


            
            #line 47 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                           Write(Strings.OnEventJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 49 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
         if (onEventJobs.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                ");


            
            #line 52 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
           Write(Strings.OnEventJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 54 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n                    <button class=\"js-jobs-list-command btn bt" +
"n-sm btn-primary\"\r\n                            data-url=\"");


            
            #line 60 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                 Write(Url.To("/onevent/trigger"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 61 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                          Write(Strings.OnEventJobsPage_Triggering);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            disabled=\"disabled\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-play-circle\"></span>\r\n                        ");


            
            #line 64 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                   Write(Strings.OnEventJobsPage_TriggerNow);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </button>\r\n\r\n                    <button class=\"js-jobs-lis" +
"t-command btn btn-sm btn-default\"\r\n                            data-url=\"");


            
            #line 68 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                 Write(Url.To("/onevent/remove"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 69 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                          Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-confirm=\"");


            
            #line 70 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                     Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            disabled=\"disabled\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-remove\"></span>\r\n                        ");


            
            #line 73 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                   Write(Strings.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </button>\r\n\r\n");


            
            #line 76 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                     if (pager != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral(" ");


            
            #line 78 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                      Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 79 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                ");



WriteLiteral("\r\n                                <th class=\"min-width\">");


            
            #line 90 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                 Write(Strings.OnEventJobsPage_Table_Signal);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"min-width\">");


            
            #line 91 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                 Write(Strings.OnEventJobsPage_Table_Trigger);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"min-width\">");


            
            #line 92 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                 Write(Strings.OnEventJobsPage_Table_Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"align-right min-width\">");


            
            #line 93 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                             Write(Strings.OnEventJobsPage_Table_LastExecution);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"align-right min-width\">");


            
            #line 94 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                             Write(Strings.Common_Created);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            </tr>\r\n                        </thead>\r\n     " +
"                   <tbody>\r\n");


            
            #line 98 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                             foreach (var job in onEventJobs)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row hover\">\r\n            " +
"                        <td>\r\n                                        <input typ" +
"e=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 102 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                                                             Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                    </td>\r\n                                " +
"    ");



WriteLiteral("\r\n\r\n                                    <td class=\"min-width\">\r\n                 " +
"                       ");



WriteLiteral("\r\n");


            
            #line 108 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                          
                                            string triggerSignal = job.TriggerSignal;

                                        

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 113 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                         if (triggerSignal != null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <code title=\"");


            
            #line 115 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                    Write(triggerSignal);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 115 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                    Write(triggerSignal);

            
            #line default
            #line hidden
WriteLiteral("</code>\r\n");


            
            #line 116 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        \r\n                                    </t" +
"d>\r\n\r\n                                    <td class=\"min-width\">\r\n              " +
"                          ");



WriteLiteral("\r\n");


            
            #line 122 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                          
                                            string triggerExpression = job.TriggerExpression;
                                        

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 126 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                         if (triggerExpression != null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <code title=\"");


            
            #line 128 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                    Write(triggerExpression);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 128 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                        Write(job.TriggerExpression);

            
            #line default
            #line hidden
WriteLiteral("</code>\r\n");


            
            #line 129 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <code>");


            
            #line 132 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                             Write(job.TriggerExpression);

            
            #line default
            #line hidden
WriteLiteral("</code>\r\n");


            
            #line 133 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n\r\n                                    " +
"<td class=\"min-width\">\r\n");


            
            #line 137 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                         if (!String.IsNullOrWhiteSpace(job.Name))
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span data-container=\"body\">");


            
            #line 139 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                   Write(job.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 140 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        \r\n                                    </t" +
"d>\r\n                                    \r\n                                    <t" +
"d class=\"align-right min-width\">\r\n");


            
            #line 145 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                         if (job.LastExecution != null)
                                        {
                                            if (!String.IsNullOrEmpty(job.LastJobId))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <a href=\"");


            
            #line 149 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                    Write(Url.JobDetails(job.LastJobId));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                                    <span class=\"label label-" +
"default label-hover\" style=\"");


            
            #line 150 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                                                     Write($"background-color: {JobHistoryRenderer.GetForegroundStateColor(job.LastJobState)};");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                                        ");


            
            #line 151 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                   Write(Html.RelativeTime(job.LastExecution.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </span>\r\n                  " +
"                              </a>\r\n");


            
            #line 154 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <em>\r\n                           " +
"                         ");


            
            #line 158 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                               Write(Strings.OnEventJobsPage_Canceled);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 158 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                                 Write(Html.RelativeTime(job.LastExecution.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </em>\r\n");


            
            #line 160 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                            }
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <em>");


            
            #line 164 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                           Write(Strings.Common_NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n");


            
            #line 165 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                    <t" +
"d class=\"align-right min-width\">\r\n");


            
            #line 168 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                         if (job.CreatedAt != null)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 170 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                       Write(Html.RelativeTime(job.CreatedAt.Value));

            
            #line default
            #line hidden
            
            #line 170 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                                                                   
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <em>N/A</em>\r\n");


            
            #line 175 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                </tr>\r" +
"\n");


            
            #line 178 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                             }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n\r\n");


            
            #line 183 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                 if (pager != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral(" ");


            
            #line 185 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                  Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 186 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");


            
            #line 188 "..\..\Dashboard\Pages\OnEventJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>    ");


        }
    }
}
#pragma warning restore 1591
